name: Build Images

on:
  push:
    paths-ignore:
      - README.md
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  ENDPOINT: ghcr.io/gerardgascon/docker-ripper

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.filter.outputs.latest }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            latest:
              - '**'
              - '!README.md'

  build:
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-latest
          - arch: arm64
            runner: ubuntu-24.04-arm

    runs-on: ${{ matrix.runner }}
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: latest/Dockerfile
          platforms: linux/${{ matrix.arch }}
          push: true
          tags: |
            ${{ env.IMAGE }}:latest-${{ matrix.arch }}
          cache-from: type=gha,scope=${{ matrix.arch }}
          cache-to: type=gha,mode=max,scope=${{ matrix.arch }}

  merge:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create and Push Manifests
        run: |
          # Create :latest (Multi-arch)
          docker buildx imagetools create \
            -t ${{ env.ENDPOINT }}:latest \
            ${{ env.ENDPOINT }}:latest-amd64 \
            ${{ env.ENDPOINT }}:latest-arm64
